version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cfarm-hr-app:latest
    container_name: cfarm_app
    restart: unless-stopped
    ports:
      - "8018:80"
    environment:
      - APP_NAME=CFARM_HR
      - APP_ENV=production
      - APP_KEY=base64:QO3JiwHh5boSk6HL7Z4RIwGSLfWnG/YfrpOufw6SNi4=
      - APP_DEBUG=true
      - APP_URL=http://192.168.7.3:8018
      - LOG_CHANNEL=stderr
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.7.3
      - DB_PORT=3308
      - DB_DATABASE=cfarm_hr
      - DB_USERNAME=itadmin
      - DB_PASSWORD=Noipalee@09
      - SESSION_DRIVER=file
