version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cfarm-hr-app:latest
    container_name: cfarm_app
    restart: unless-stopped
    environment:
      - APP_NAME=CFARM_HR
      - APP_ENV=production
      - APP_KEY=base64:QO3JiwHh5boSk6HL7Z4RIwGSLfWnG/YfrpOufw6SNi4=
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - LOG_CHANNEL=stderr
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.7.3
      - DB_PORT=3308
      - DB_DATABASE=cfarm_hr
      - DB_USERNAME=itadmin
      - DB_PASSWORD=Noipalee@09
      - SESSION_DRIVER=file
    volumes:
      - cfarm-data-v2:/var/www
    networks:
      - cfarm-network

  webserver:
    image: nginx:alpine
    container_name: cfarm_nginx
    restart: unless-stopped
    ports:
      - "8018:80"
    volumes:
      - cfarm-data-v2:/var/www
    command: /bin/sh -c "cp /var/www/docker/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app
    networks:
      - cfarm-network

networks:
  cfarm-network:
    driver: bridge

volumes:
  cfarm-data-v2:
